name: ci
run-name: "build & test"

on: [push]

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y build-essential cmake

      - name: Task 1 (arcsin)
        run: |
          cd 1-arcsin
          mkdir -p build
          cd build
          cmake .. && cmake --build .
          ./tests

      - name: Task 2 (bubblesort)
        run: |
          cd 2-bubble-sort
          mkdir -p build
          cd build
          cmake .. && cmake --build .
          ./tests

      - name: Task 3
        run: |
          # TODO: 
